# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
