# Generated by Django 2.2.7 on 2019-11-17 10:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('empty_candidate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usertoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('invalidated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_name', models.CharField(max_length=50)),
                ('voting_description', models.CharField(blank=True, max_length=200)),
                ('max_votes', models.IntegerField(default=1)),
                ('is_open', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField(default=0)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.Voting')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.Candidate')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.Voting')),
            ],
        ),
        migrations.CreateModel(
            name='TokenMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.Usertoken')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.Voting')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.Voting'),
        ),
    ]
