# Generated by Django 3.1.3 on 2020-11-10 23:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vaalikoppi.candidate_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Usertoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('invalidated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.candidate')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vaalikoppi.vote_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='VoterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertoken_token', models.CharField(max_length=50)),
                ('usertoken_alias', models.CharField(blank=True, max_length=50)),
                ('has_voted', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vaalikoppi.voterstatus_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_name', models.CharField(max_length=50)),
                ('voting_description', models.CharField(blank=True, max_length=200)),
                ('max_votes', models.IntegerField(default=1)),
                ('is_open', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('treshold', models.FloatField(default=500.0)),
                ('is_password_protected', models.BooleanField(default=False)),
                ('voting_password', models.CharField(blank=True, max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vaalikoppi.voting_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vaalikoppi.votingresult_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='NormalVoting',
            fields=[
                ('voting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.voting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.voting',),
        ),
        migrations.CreateModel(
            name='RankedChoiceVoting',
            fields=[
                ('voting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.voting')),
                ('voting_round', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.voting',),
        ),
        migrations.CreateModel(
            name='TokenMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_vaalikoppi.tokenmapping_set+', to='contenttypes.contenttype')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.usertoken')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TransferableVotingVoterStatus',
            fields=[
                ('voterstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.voterstatus')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.rankedchoicevoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.voterstatus',),
        ),
        migrations.CreateModel(
            name='RankedChoiceVotingResult',
            fields=[
                ('votingresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.votingresult')),
                ('vote_rounds', models.IntegerField(default=1)),
                ('elected', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_results', to='vaalikoppi.rankedchoicevoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.votingresult',),
        ),
        migrations.CreateModel(
            name='RankedChoiceVoteGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_transferred', models.BooleanField(default=False)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.rankedchoicevoting')),
            ],
        ),
        migrations.CreateModel(
            name='RankedChoiceVote',
            fields=[
                ('vote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.vote')),
                ('preference', models.IntegerField(default=0)),
                ('votegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.rankedchoicevotegroup')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.rankedchoicevoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.vote',),
        ),
        migrations.CreateModel(
            name='RankedChoiceTokenMapping',
            fields=[
                ('tokenmapping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.tokenmapping')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.rankedchoicevoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.tokenmapping',),
        ),
        migrations.CreateModel(
            name='RankedChoiceCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.candidate')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vaalikoppi.rankedchoicevoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.candidate',),
        ),
        migrations.CreateModel(
            name='NormalVotingVoterStatus',
            fields=[
                ('voterstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.voterstatus')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.normalvoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.voterstatus',),
        ),
        migrations.CreateModel(
            name='NormalVotingResult',
            fields=[
                ('votingresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.votingresult')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_results', to='vaalikoppi.normalvoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.votingresult',),
        ),
        migrations.CreateModel(
            name='NormalVote',
            fields=[
                ('vote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.vote')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.normalvoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.vote',),
        ),
        migrations.CreateModel(
            name='NormalTokenMapping',
            fields=[
                ('tokenmapping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.tokenmapping')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.normalvoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.tokenmapping',),
        ),
        migrations.CreateModel(
            name='NormalCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaalikoppi.candidate')),
                ('empty_candidate', models.BooleanField(default=False)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vaalikoppi.normalvoting')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vaalikoppi.candidate',),
        ),
    ]
