# Generated by Django 3.1.3 on 2020-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalvotingresult',
            name='vote_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rankedchoicevotingresult',
            name='vote_count',
            field=models.FloatField(default=0),
        ),
    ]
