# Generated by Django 3.1.2 on 2020-11-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voting',
            name='voting_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='votingtransferable',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votingtransferable',
            name='voting_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
