# Generated by Django 3.1.3 on 2020-11-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalvotingresult',
            name='vote_share',
            field=models.FloatField(default=0.0),
        ),
    ]
