# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='question_text',
            new_name='voting_name',
        ),
        migrations.AddField(
            model_name='voting',
            name='voting_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
