# Generated by Django 3.1.8 on 2023-09-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0002_auto_20201123_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalvoting',
            name='hide_vote_counts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rankedchoicevoting',
            name='hide_vote_counts',
            field=models.BooleanField(default=False),
        ),
    ]
