# Generated by Django 3.1.2 on 2020-11-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0002_auto_20201102_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='has_password',
            new_name='is_password_protected',
        ),
        migrations.RenameField(
            model_name='votingtransferable',
            old_name='has_password',
            new_name='is_password_protected',
        ),
    ]
