# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0003_auto_20171029_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
