# Generated by Django 3.1.2 on 2020-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0003_auto_20201102_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
