# Generated by Django 3.1.3 on 2020-11-06 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0004_usertoken_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterStatusTransferable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertoken_token', models.CharField(max_length=50)),
                ('usertoken_alias', models.CharField(blank=True, max_length=50)),
                ('has_voted', models.BooleanField(default=True)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.votingtransferable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoterStatusRegular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertoken_token', models.CharField(max_length=50)),
                ('usertoken_alias', models.CharField(blank=True, max_length=50)),
                ('has_voted', models.BooleanField(default=True)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.voting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
