# Generated by Django 3.1.3 on 2020-11-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaalikoppi', '0005_voterstatusregular_voterstatustransferable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingroundtransferable',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaalikoppi.votingtransferable'),
        ),
    ]
